[package]
name = "rfid-checker"
description = "A RFIDs uniqueness checker"
version = "1.0.0"
edition = "2018"
authors = ["Michal Takac <hello@michaltakac.com>"]

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }
